import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'doc',
        id: 'README',
      },
      collapsed: false,
      items: [
        'getting-started/oncall-users',
        'getting-started/team-admins',
        'getting-started/account-admins',        
      ]
    },
    'architecture-guide',
    'common-ui-design-patterns',
    'alerts',
    'teams',
    'schedules',
    'escalation-policies',
    'integrations',
    'broadcasts',
    'users',
    'notifications',
    'reports',
    'billing',
    'accounts',
    'stakeholders',
    'maintenance-windows',
    'routers',
    'notification-rules',
    'single-sign-on-sso',
    'email-to-text',
  ],

  apiSidebar: [
    'api/introduction',
    'api/authentication',
    'api/errors',
    'api/pagination-and-filters',
    'api/common-model-attributes',
    'api/account-users',
    'api/alerts',
    'api/broadcasts',
    'api/comments',
    'api/escalation-policies',
    'api/events',
    'api/integrations',
    'api/logs',
    'api/maintenance-windows',
    'api/notification-rules',
    'api/routers',
    'api/schedules',
    'api/teams',
    'api/users',
  ],

  integrationGuidesSidebar: [
    'integration-guides/introduction',
    'integration-guides/66uptime',
    'integration-guides/apex-ping',
    'integration-guides/appdynamics',
    'integration-guides/auvik',
    'integration-guides/aws-cloudwatch',
    'integration-guides/azure-monitor',
    'integration-guides/cloudflare',
    'integration-guides/custom-webhook',
    'integration-guides/cronitor',
    'integration-guides/datadog',
    'integration-guides/dead-mans-snitch',
    'integration-guides/dynatrace',
    'integration-guides/echoes-hq',
    'integration-guides/elastalert',
    'integration-guides/email',
    'integration-guides/form',
    'integration-guides/freshdesk',
    'integration-guides/freshservice',
    'integration-guides/google-hangouts-chat',
    'integration-guides/grafana',
    'integration-guides/healthchecks',
    'integration-guides/hetrix-tools',
    'integration-guides/honeybadger',
    'integration-guides/hydrozen',
    'integration-guides/hyperping',
    'integration-guides/jira-server',
    'integration-guides/jotform',
    'integration-guides/kapacitor',
    'integration-guides/logic-monitor',
    {
      type: 'category',
      label: 'Mattermost',
      link: {
        type: 'doc',
        id: 'integration-guides/mattermost/README',
      },
      items: [
        'integration-guides/mattermost/outgoing-webhook',
        'integration-guides/mattermost/post-to-channel',
      ],
    },
    'integration-guides/meta-workplace',
    'integration-guides/microsoft-teams',
    'integration-guides/new-relic',
    'integration-guides/outgoing-webhook',
    'integration-guides/pingdom',
    'integration-guides/prometheus',
    'integration-guides/prtg-network-monitor',
    'integration-guides/pulsetic',
    'integration-guides/scom',
    'integration-guides/sentry',
    'integration-guides/serverguard24',
    'integration-guides/site24x7',
    {
      type: 'category',
      label: 'Slack',
      link: {
        type: 'doc',
        id: 'integration-guides/slack/README',
      },
      items: [
        'integration-guides/slack/notifications',
        'integration-guides/slack/outgoing-webhook',
        'integration-guides/slack/post-to-channel',
      ],
    },
    'integration-guides/solarwinds',
    'integration-guides/stackdriver',
    'integration-guides/statuscake',
    'integration-guides/status-gator',
    {
      type: 'category',
      label: 'Twilio',
      link: {
        type: 'doc',
        id: 'integration-guides/twilio/README',
      },
      items: [
        'integration-guides/twilio/incoming-sms',
        'integration-guides/twilio/live-call-routing',
      ],
    },
    'integration-guides/typeform',
    'integration-guides/uptime-kuma',
    'integration-guides/uptime',
    'integration-guides/uptimerobot',
    'integration-guides/webhook',
    'integration-guides/zabbix',
    'integration-guides/zendesk',
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
